name: CI (Test and Build)
on: pull_request
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: ./ui/.nvmrc

      - name: Install Dependencies
        run: npm ci
        working-directory: ./ui

      - name: Run Lint
        run: npm run lint
        working-directory: ./ui

      - name: Run Tests
        run: npm run test -- run
        working-directory: ./ui

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests for Groups
        run: npm run e2e
        working-directory: ./ui

      - name: Run E2E Tests for Talk
        run: npm run e2e:chat
        working-directory: ./ui

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Build
        run: npm run build
        working-directory: ./ui
