name: Deploy Groups
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the tag to deploy
  push:
    branches:
      - 'develop'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Create and deploy a glob to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./ui/.nvmrc
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Build Frontend
        working-directory: ./ui
        run: |
          npm ci
          npm run build
      - id: glob
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'desk/desk.docket-0'
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add desk/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          INPUT=${{ github.event.inputs.tag }}
          BRANCH=${INPUT:-"develop"}
          git pull origin $BRANCH --rebase --autostash
          git push
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/landscape-apps groups wannec-dozzod-marzod us-west1-b ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.JANEWAY_SSH_PUB_KEY }}
